### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by vbergae** [reednj/TDSemiModal#20]
There are plans to continue his development?

**Comment by reednj** [comment]
I  don't a Mac any more, so its not possible for me to continue
development. If someone wants to take it and update this for iOS8 I
wouldn't have a problem with it.

**Comment by alejandroluengo** [comment]
reednj I will be happy to continue with this project if you want

**Comment by vbergae** [comment]
I also want to help. Where do we start?

**Comment by vbergae** [comment]
Ok, I was working on some changes and upgrades and created pull request #21 

Please check it and approve if you agree with it or leave some comments to be fixed. I think the next step should be to upgrade the pod.

**Comment by reednj** [comment]
I think the changes look ok, although its hard to tell without being able to test them.

Like I said, I am happy for someone to take over development, and since it looks like you put some work into this PR to modernize things, I have made you a collaborator on this repository. Merge the PR if you are happy with it.

**Comment by vbergae** [comment]
Perfect, thank you Nathan ;)

**Comment by jenhausu** [comment]
###### A little advice

Why not just transfer this Repo to vbergae or someone else?
It will be more convenient to maintain this project.

**Comment by reednj** [comment]
Vbergae is already a full contributor. He is the maintainer of this project
now.

**Comment by jenhausu** [comment]
ok, I got it.
